# Needs to be run from the project root context e.g. `cd sourcify/ && docker build -f services/4byte/Dockerfile .`

# Builder image
FROM node:22.22.0-bookworm@sha256:20a424ecd1d2064a44e12fe287bf3dae443aab31dc5e0c0cb6c74bef9c78911c as builder

RUN mkdir -p /home/app
WORKDIR /home/app

COPY . .

# Install 4byte service's dependencies and build
RUN npm ci --workspace=sourcify-4byte --include-workspace-root
RUN npx lerna run build --scope sourcify-4byte

######################
## Production image ##
######################
FROM node:22.22.0-trixie-slim@sha256:465a8c8f0f4103861bcbcf3e512608394b7155eccb1955425f4ea3f672ddc53e as production

RUN mkdir -p /home/app/services/4byte

WORKDIR /home/app/
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
COPY lerna.json ./lerna.json
COPY nx.json ./nx.json

COPY --from=builder /home/app/services/4byte/ ./services/4byte/

RUN npm ci --workspace=sourcify-4byte --include-workspace-root --omit=dev

LABEL org.opencontainers.image.source https://github.com/argotorg/sourcify
LABEL org.opencontainers.image.licenses MIT

# Set default value for ARG
ARG NODE_ENV=production
ARG PORT=80

# Set environment variable
ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}

WORKDIR /home/app/services/4byte
# node command has to be used directly for SIGTERM handling (NOT npm start)
CMD ["node", "dist/cli.js"]