version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0
  
workflows:
  # Always run
  node-build:
    jobs:
      - node-v22
  # Has to run always. Can't regex filter on add-chain-{chainId} branch names see: https://stackoverflow.com/questions/55839004/circleci-regex-filtering-match-within-string
  test-new-chain:
    jobs:
      - test-new-chain

jobs:
  node-v22:
    docker:
      - image: cimg/node:22.4.1
      - image: postgres:16-alpine
        environment:
          POSTGRES_DB: sourcify
          POSTGRES_USER: sourcify
          POSTGRES_PASSWORD: sourcify

    working_directory: ~/sourcify
    parameters:
      run_coveralls:
        type: boolean
        default: false
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: lint
          command: npm run lerna-lint
      - run:
          name: tsc and test
          command: npx lerna run build && npx lerna run lerna-test
          environment:
            DOCKER_HOST_POSTGRES_TEST_PORT: 5432
            SOURCIFY_POSTGRES_HOST: "localhost"
            SOURCIFY_POSTGRES_DB: "sourcify"
            SOURCIFY_POSTGRES_USER: "sourcify"
            SOURCIFY_POSTGRES_PASSWORD: "sourcify"
            SOURCIFY_POSTGRES_PORT: 5432
      - run:
          name: create lcov reports
          command: npx lerna run cov:lcov
      - codecov/upload
    resource_class: large
  test-new-chain:
    docker:
      - image: cimg/node:22.4.1
      - image: postgres:16-alpine
        environment:
          POSTGRES_DB: sourcify
          POSTGRES_USER: sourcify
          POSTGRES_PASSWORD: sourcify
    resource_class: small
    working_directory: ~/sourcify
    steps:
      - checkout
      - run:
          name: check if a new chain PR
          command: ./.circleci/scripts/test_new_chain_support.sh
      - run:
          name: Check NEW_CHAIN_ID existence
          command: |
            echo "NEW_CHAIN_ID=$NEW_CHAIN_ID"
            if [ -z "${NEW_CHAIN_ID}" ]; then
              echo 'NEW_CHAIN_ID is unset or empty, skipping subsequent steps.'
              circleci-agent step halt
            fi
      - run:
          name: install build and test
          command: npm install && npx lerna run build --scope=sourcify-server && cd services/server && npm run postgres-test:migrate && npm run test:chains
          environment:
            DOCKER_HOST_POSTGRES_TEST_PORT: 5432
            SOURCIFY_POSTGRES_HOST: "localhost"
            SOURCIFY_POSTGRES_DB: "sourcify"
            SOURCIFY_POSTGRES_USER: "sourcify"
            SOURCIFY_POSTGRES_PASSWORD: "sourcify"
            SOURCIFY_POSTGRES_PORT: 5432
