version: 2.1

# Parameter that can be passed in this pipeline have to be defined here too. Used with nightly.
parameters:
  run-nightly:
    type: boolean
    default: false

aliases:
  - &monitor-e2e-base
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: checkout metacoin-source-verify
          command: cd ~/project && git clone git@github.com:sourcifyeth/metacoin-source-verify.git
      - run:
          name: install
          command: cd ~/project/metacoin-source-verify && npm ci
      - run:
          name: monitor test
          command: cd ~/project/metacoin-source-verify && ./scripts/monitor_e2e.sh
          no_output_timeout: 30m
    docker:
      - image: cimg/node:22.22.0@sha256:2c1320ee6a256628f698938038700911276310d40cc9887cfc8f66ec0daa4343
  - &verification-e2e-base
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: checkout metacoin-source-verify
          command: cd ~/project && git clone git@github.com:sourcifyeth/metacoin-source-verify.git
      - run:
          name: install
          command: cd ~/project/metacoin-source-verify && npm ci
      - run:
          name: verification test
          command: cd ~/project/metacoin-source-verify && ./scripts/verification_e2e.sh
      - store_artifacts:
          path: ~/project/metacoin-source-verify/verified-contracts
    docker:
      - image: cimg/node:22.22.0@sha256:2c1320ee6a256628f698938038700911276310d40cc9887cfc8f66ec0daa4343

workflows:
  e2e-tests:
    jobs:
      - monitor-e2e-sepolia
      - monitor-e2e-hoodi
      - verification-e2e-sepolia
      - verification-e2e-hoodi

jobs:
  monitor-e2e-sepolia:
    <<: *monitor-e2e-base
    environment:
      CHAIN_ID: "11155111"
      CHAIN_NAME: sepolia
  monitor-e2e-hoodi:
    <<: *monitor-e2e-base
    environment:
      CHAIN_ID: "560048"
      CHAIN_NAME: hoodi
  verification-e2e-sepolia:
    <<: *verification-e2e-base
    environment:
      CHAIN_ID: "11155111"
      CHAIN_NAME: sepolia
  verification-e2e-hoodi:
    <<: *verification-e2e-base
    environment:
      CHAIN_ID: "560048"
      CHAIN_NAME: hoodi
