version: 2.1

# Parameter that can be passed in this pipeline have to be defined here too.
parameters:
  run-test-chains-regularly:
    type: boolean
    default: false

workflows:
  test-chains-regularly:
    jobs:
      - test-chains

jobs:
  test-chains:
    working_directory: ~/sourcify
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build and test
          command: npx lerna run build && npx lerna run test:chains          
          environment:
            DOCKER_HOST_POSTGRES_TEST_PORT: 5432
            SOURCIFY_POSTGRES_HOST: "localhost"
            SOURCIFY_POSTGRES_DB: "sourcify"
            SOURCIFY_POSTGRES_USER: "sourcify"
            SOURCIFY_POSTGRES_PASSWORD: "sourcify"
            SOURCIFY_POSTGRES_PORT: 5432
      - store_artifacts: # Store and publish test results for reference
          path: ./services/server/chain-tests-report
    docker:
      - image: cimg/node:22.4.1
      - image: postgres:16-alpine
        environment:
          POSTGRES_DB: sourcify
          POSTGRES_USER: sourcify
          POSTGRES_PASSWORD: sourcify
