version: "3.8"

services:
  db:
    image: postgres:15-alpine@sha256:3d0f7584ed7d04e27fa050d6683a74746608faf21f202be78460d679cc56461f
    environment:
      POSTGRES_DB: "sourcify"
      POSTGRES_USER: "sourcify"
      POSTGRES_PASSWORD: "sourcify"
    ports:
      - 5431:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Needed to separate the migration because node must have PID 1 in service server
  run-migrations:
    image: node:22.22.0-bookworm-slim@sha256:dd9d21971ec4395903fa6143c2b9267d048ae01ca6d3ea96f16cb30df6187d94
    volumes:
      - ../database:/home/app/services/database
    environment:
      DATABASE_URL: "postgres://sourcify:sourcify@db:5432/sourcify?sslmode=disable"
    command: /bin/bash -c "cd /home/app/services/database && npm install && npm run migrate:up"
    restart: "no"
    deploy:
      restart_policy:
        condition: none
    depends_on:
      db:
        condition: service_healthy

  server:
    build:
      context: ../..
      dockerfile: services/server/Dockerfile
    ports:
      - "5555:5555"
    env_file:
      - .env
    volumes:
      - ./src/config/local.js:/home/app/services/server/dist/config/local.js
    depends_on:
      db:
        condition: service_started
      run-migrations:
        condition: service_completed_successfully
